### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lde/wirecard/accept/sdk/extensions/PaymentFlowController$Device;

### ISSUE THREAD

**Issue by doerschner** [mposSVK/acceptSDK-Android#14]
Hey guys, sadly I have to open another ticket regarding version 1.5.10.1.

stacktrace: 
1.)
```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lde/wirecard/accept/sdk/extensions/PaymentFlowController$Device;
    at de.wirecard.accept.extension.refactor.AcceptThyronPaymentFlowController.convertPairedBluetoothDevices(AcceptThyronPaymentFlowController.java:131)
    at de.wirecard.accept.extension.refactor.AcceptThyronPaymentFlowController.discoverDevices(AcceptThyronPaymentFlowController.java:99)
    at wp.a(WirecardConnectionImpl.java:72)
    at ws.a(WirecardManager.java:75)
    at ws.a(WirecardManager.java:82)
    at yn.loadInBackground(PurchaseInitialLoaderObjectLoader.java:146)
    at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
    at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
    at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
    at android.os.AsyncTask$2.call(AsyncTask.java:304)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    ... 3 more
```
2.)
```
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lde/wirecard/accept/sdk/extensions/PaymentFlowController$Device;
                                                                        at de.wirecard.accept.extension.refactor.AcceptThyronPaymentFlowController.convertPairedBluetoothDevices(AcceptThyronPaymentFlowController.java:131)
                                                                        at de.wirecard.accept.extension.refactor.AcceptThyronPaymentFlowController.discoverDevices(AcceptThyronPaymentFlowController.java:99)
```

I cleaned, rebuilded and reinstalled the app.

**Comment by doerschner** [comment]
this seems to be the same issue: somehow somewhat wants to access die Device subclass in PaymentFlowController, which doesn't seem to exist anymore. I had to change from PaymentFlowController.Device to Device in our whole app, too.

**Comment by doerschner** [comment]
Our initialization of the AcceptSDK:
```
AcceptSDK.init(appContext.getApplicationContext(),
                    CLIENT_ID,
                    CLIENT_SECRET,
                    API_PATH);
AcceptSDK.loadExtensions(appContext.getApplicationContext(), null, false);
AcceptSDK.setPrefTimeout(7); //timeout for requests
AcceptSDK.setPaymentCallbackURL(CALLBACK_URL);
```
The constants are, i guess, irrelevant, so i didn't link them. is that the correct way to use ist?

**Comment by WirecardMobileServices** [comment]
Yes, its correct.

Related to PaymentFlowController.Device ..its still ongoing this issue.
Pls make again clean, rebuild and reinstall with 1.5.10.1 ...if you will be having some problems.. try 1.5.10.2 
pls check also [compatibility table](https://github.com/WirecardMobileServices/acceptSDK-Android#extension-compatibility-table)

We are able to build our app using dependencies to GitHub.  Not sure what can cause so strange problem

thx.
