### ISSUE TITLE
Sample crashes with "Call AcceptSDK.init() before calling setPrefTimeout()"

### ISSUE THREAD

**Issue by mpost** [mposSVK/acceptSDK-Android#3]
``` java
Caused by: java.lang.IllegalStateException: Call AcceptSDK.init() before calling setPrefTimeout()
 at de.wirecard.accept.sdk.AcceptSDK.instanceCheck(AcceptSDK.java:458)
 at de.wirecard.accept.sdk.AcceptSDK.setPrefTimeout(AcceptSDK.java:1297)
 at de.wirecard.accept.sample.Application.onCreate(Application.java:45)
```

**Comment by WirecardMobileServices** [comment]
;) Hi, You have to call AcceptSDK.init() before calling setPrefTimeout()..this is all.

Sorry some initialization methods have higher priority. In new version it will be no so strict.

**Comment by rameshpaladugu** [comment]
Hi,
I am calling AcceptSDK.init() before setPrefTimeout() but still the app crashes. Can you help me in this

**Comment by WirecardMobileServices** [comment]
Hi, rameshpaladugu. 
From your logs print screen i see that your issue is about something different.
because it is caused by:

public boolean getBoolean (int id)

Looks like you are missing some resources... (project is not build) ... because resource is in lib.

We are using Android Studio.
